SRC :=
SRC += parser/code/source/MessageParser/ChannelMessages/MessageChannelInviteParser.cpp \
parser/code/source/MessageParser/ChannelMessages/MessageChannelJoinParser.cpp \
parser/code/source/MessageParser/ChannelMessages/MessageChannelKickParser.cpp \
parser/code/source/MessageParser/ChannelMessages/MessageChannelListParser.cpp \
parser/code/source/MessageParser/ChannelMessages/MessageChannelModeParser.cpp \
parser/code/source/MessageParser/ChannelMessages/MessageChannelNamesParser.cpp \
parser/code/source/MessageParser/ChannelMessages/MessageChannelPartParser.cpp \
parser/code/source/MessageParser/ChannelMessages/MessageChannelTopicParser.cpp \
parser/code/source/MessageParser/ConnectionMessages/MessageConnectionModeParser.cpp \
parser/code/source/MessageParser/ConnectionMessages/MessageConnectionNickParser.cpp \
parser/code/source/MessageParser/ConnectionMessages/MessageConnectionOperParser.cpp \
parser/code/source/MessageParser/ConnectionMessages/MessageConnectionPassParser.cpp \
parser/code/source/MessageParser/ConnectionMessages/MessageConnectionQuitParser.cpp \
parser/code/source/MessageParser/ConnectionMessages/MessageConnectionUserParser.cpp \
parser/code/source/MessageParser/MessageParameterCommonParser.cpp \
parser/code/source/MessageParser/MessageParameterValidator.cpp \
parser/code/source/MessageParser/MessageParser.cpp \
parser/code/source/MessageParser/MixedParsers/ModeParser.cpp \
parser/code/source/MessageParser/PrivateMessages/MessagePrivateMessagesNoticeParser.cpp \
parser/code/source/MessageParser/PrivateMessages/MessagePrivateMessagesPrivmsgParser.cpp \
parser/code/source/MessageParser/ServerMessages/MessageServerAdminParser.cpp \
parser/code/source/MessageParser/ServerMessages/MessageServerInfoParser.cpp \
parser/code/source/MessageParser/ServerMessages/MessageServerMotdParser.cpp \
parser/code/source/MessageParser/ServerMessages/MessageServerSqueryParser.cpp \
parser/code/source/MessageParser/ServerMessages/MessageServerStatsParser.cpp \
parser/code/source/MessageParser/ServerMessages/MessageServerTimeParser.cpp \
parser/code/source/MessageParser/ServerMessages/MessageServerVersionParser.cpp \
parser/code/source/MessageParser/UserMessages/MessageUserErrorParser.cpp \
parser/code/source/MessageParser/UserMessages/MessageUserKillParser.cpp \
parser/code/source/MessageParser/UserMessages/MessageUserPingParser.cpp \
parser/code/source/MessageParser/UserMessages/MessageUserPongParser.cpp \
parser/code/source/MessageParser/UserMessages/MessageUserWhoisParser.cpp \
parser/code/source/MessageParser/UserMessages/MessageUserWhoParser.cpp \
parser/code/source/MessageParser/UserMessages/MessageUserWhowasParser.cpp \
parser/code/source/ParsedMessage/ChannelMessages/ParsedMessageChannelInvite.cpp \
parser/code/source/ParsedMessage/ChannelMessages/ParsedMessageChannelJoin.cpp \
parser/code/source/ParsedMessage/ChannelMessages/ParsedMessageChannelKick.cpp \
parser/code/source/ParsedMessage/ChannelMessages/ParsedMessageChannelList.cpp \
parser/code/source/ParsedMessage/ChannelMessages/ParsedMessageChannelMode.cpp \
parser/code/source/ParsedMessage/ChannelMessages/ParsedMessageChannelNames.cpp \
parser/code/source/ParsedMessage/ChannelMessages/ParsedMessageChannelPart.cpp \
parser/code/source/ParsedMessage/ChannelMessages/ParsedMessageChannelTopic.cpp \
parser/code/source/ParsedMessage/ConnectionMessages/ParsedMessageConnectionMode.cpp \
parser/code/source/ParsedMessage/ConnectionMessages/ParsedMessageConnectionNick.cpp \
parser/code/source/ParsedMessage/ConnectionMessages/ParsedMessageConnectionOper.cpp \
parser/code/source/ParsedMessage/ConnectionMessages/ParsedMessageConnectionPass.cpp \
parser/code/source/ParsedMessage/ConnectionMessages/ParsedMessageConnectionQuit.cpp \
parser/code/source/ParsedMessage/ConnectionMessages/ParsedMessageConnectionUser.cpp \
parser/code/source/ParsedMessage/ParsedMessage.cpp \
parser/code/source/ParsedMessage/PrivateMessages/ParsedMessagePrivateMessagesNotice.cpp \
parser/code/source/ParsedMessage/PrivateMessages/ParsedMessagePrivateMessagesPrivmsg.cpp \
parser/code/source/ParsedMessage/ServerMessages/ParsedMessageServerAdmin.cpp \
parser/code/source/ParsedMessage/ServerMessages/ParsedMessageServerInfo.cpp \
parser/code/source/ParsedMessage/ServerMessages/ParsedMessageServerMotd.cpp \
parser/code/source/ParsedMessage/ServerMessages/ParsedMessageServerSquery.cpp \
parser/code/source/ParsedMessage/ServerMessages/ParsedMessageServerStats.cpp \
parser/code/source/ParsedMessage/ServerMessages/ParsedMessageServerTime.cpp \
parser/code/source/ParsedMessage/ServerMessages/ParsedMessageServerVersion.cpp \
parser/code/source/ParsedMessage/UserMessages/ParsedMessageUserError.cpp \
parser/code/source/ParsedMessage/UserMessages/ParsedMessageUserKill.cpp \
parser/code/source/ParsedMessage/UserMessages/ParsedMessageUserPing.cpp \
parser/code/source/ParsedMessage/UserMessages/ParsedMessageUserPong.cpp \
parser/code/source/ParsedMessage/UserMessages/ParsedMessageUserWho.cpp \
parser/code/source/ParsedMessage/UserMessages/ParsedMessageUserWhois.cpp \
parser/code/source/ParsedMessage/UserMessages/ParsedMessageUserWhowas.cpp \
lexer/code/source/LexedMessage/LexedMessage.cpp \
lexer/code/source/MessageLexer/MessageLexer.cpp \
command_executor/code/source/commands/command_chanmode.cpp \
command_executor/code/source/commands/command_invite.cpp \
command_executor/code/source/commands/command_join.cpp \
command_executor/code/source/commands/command_kick.cpp \
command_executor/code/source/commands/command_kill.cpp \
command_executor/code/source/commands/command_list.cpp \
command_executor/code/source/commands/command_mode.cpp \
command_executor/code/source/commands/command_motd.cpp \
command_executor/code/source/commands/command_names.cpp \
command_executor/code/source/commands/command_nick.cpp \
command_executor/code/source/commands/command_notice.cpp \
command_executor/code/source/commands/command_oper.cpp \
command_executor/code/source/commands/command_part.cpp \
command_executor/code/source/commands/command_pass.cpp \
command_executor/code/source/commands/command_ping.cpp \
command_executor/code/source/commands/command_pong.cpp \
command_executor/code/source/commands/command_privmsg.cpp \
command_executor/code/source/commands/command_quit.cpp \
command_executor/code/source/commands/command_stats.cpp \
command_executor/code/source/commands/command_time.cpp \
command_executor/code/source/commands/command_topic.cpp \
command_executor/code/source/commands/command_user.cpp \
command_executor/code/source/commands/command_version.cpp \
command_executor/code/source/commands/mixed_command_mode.cpp \
command_executor/code/source/commands/send_message_to_users_in_chan.cpp \
command_executor/code/source/executor/CommandExecutor.cpp \
command_executor/code/source/ServerInfo/ServerInfo.cpp \
input_stream_orquestator/code/source/LexerParserConnector/LexerParserConnector.cpp \
database/db/Chan.cpp \
database/db/ChanId.cpp \
database/db/Client.cpp \
database/db/ClientData.cpp \
database/db/ClientId.cpp \
database/db/Database.cpp \
database/db/exceptions/InvalidId.cpp \
database/db/exceptions/InvalidState.cpp \
database/db/exceptions/RegisterNotFound.cpp \
database/db/IdManager.cpp \
database/db/Key.cpp \
database/db/strings/equalsNoCase.cpp \
database/db/strings/toLower.cpp \
database/db/strings/toUpper.cpp \
database/db/TextMask.cpp \
database/db/Unregistered.cpp \
sockets/src/aux_server.cpp \
sockets/src/com.cpp \
sockets/src/com_exceptions.cpp \
sockets/src/gest_signal.cpp \
sockets/src/internal_commands.cpp \
sockets/src/log.cpp \
sockets/src/log_exceptions.cpp \
sockets/src/main.cpp \
sockets/src/main_resp.cpp \
sockets/src/msg.cpp \
sockets/src/orchestator.cpp \
sockets/src/orchestator_exceptions.cpp \
sockets/src/others.cpp \
sockets/src/replies.cpp \
sockets/src/replies_exception.cpp \
sockets/src/replies_generator.cpp \
sockets/src/send_message_to_user_vector.cpp \
sockets/src/time_control.cpp \
sockets/src/tommy_commands.cpp \
sockets/src/user.cpp \
main_loop/CommandActionAssociator.cpp \
main_loop/main_loop.cpp

OBJ_DIR := obj
OBJ := $(SRC:%.cpp=$(OBJ_DIR)/%.o)

NAME := irc

CXX := g++ -std=c++98
CXXFLAGS := -Wall -Wextra -Werror # TODO -g3 -fsanitize=address  for sanitize compiling
CPPFLAGS := -MMD
LDFLAGS := # TODO -fsanitize=address for sanitize compiling

#Directories
#SRC_DIR := src
#OBJ_DIR := obj
DEP_DIR := $(OBJ_DIR)

#Full relpath of sources, objects and dependency files
#OBJ := $(SRC:%.cpp=$(OBJ_DIR)/%.o)
DEP := $(SRC:%.cpp=$(DEP_DIR)/%.d)
#SRC := $(addprefix $(SRC_DIR)/, $(SRC))


# Rules
all: $(NAME)

print:
	@echo "Sources: \n" $(SRC)
	@echo "Objects: \n" $(OBJ)
	@echo "Dependecies: \n" $(DEP)

$(OBJ_DIR)/%.o: %.cpp
	@mkdir -p $(@D)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -o $@ -c $<

$(NAME): $(OBJ)
	@echo "Frankenstein powered by Javgonza, Vicmarti & Tomartin in 42Madrid"
	$(COMPILER_COMMAND) $(LINKER_FLAGS) $(OBJ) -o $(NAME)

bonus: all

# clean rule
clean:
#	@make -C ./src/tests tests_clean
	@rm -Rf $(OBJ_DIR)
	@echo "Objects removed!"

# fclean rule
fclean: clean
	@rm -f $(NAME)
	@echo "$(NAME) removed!"

# re rule
re: fclean all

# phony
.PHONY: all clean fclean re

# default
.DEFAULT_GOAL := all
