#ifndef ALLMESSAGEPARSERS_HPP
# define ALLMESSAGEPARSERS_HPP

#include "code/source/MessageParser/MixedParsers/ModeParser.hpp"
#include "code/source/MessageParser/ChannelMessages/MessageChannelInviteParser.hpp"
#include "code/source/MessageParser/ChannelMessages/MessageChannelJoinParser.hpp"
#include "code/source/MessageParser/ChannelMessages/MessageChannelKickParser.hpp"
#include "code/source/MessageParser/ChannelMessages/MessageChannelListParser.hpp"
#include "code/source/MessageParser/ChannelMessages/MessageChannelModeParser.hpp"
#include "code/source/MessageParser/ChannelMessages/MessageChannelNamesParser.hpp"
#include "code/source/MessageParser/ChannelMessages/MessageChannelPartParser.hpp"
#include "code/source/MessageParser/ChannelMessages/MessageChannelTopicParser.hpp"
#include "code/source/MessageParser/ConnectionMessages/MessageConnectionModeParser.hpp"
#include "code/source/MessageParser/ConnectionMessages/MessageConnectionNickParser.hpp"
#include "code/source/MessageParser/ConnectionMessages/MessageConnectionOperParser.hpp"
#include "code/source/MessageParser/ConnectionMessages/MessageConnectionPassParser.hpp"
#include "code/source/MessageParser/ConnectionMessages/MessageConnectionQuitParser.hpp"
#include "code/source/MessageParser/ConnectionMessages/MessageConnectionUserParser.hpp"
#include "code/source/MessageParser/MessageParameterCommonParser.hpp"
#include "code/source/MessageParser/MessageParameterValidator.hpp"
#include "code/source/MessageParser/MessageParser.hpp"
#include "code/source/MessageParser/PrivateMessages/MessagePrivateMessagesNoticeParser.hpp"
#include "code/source/MessageParser/PrivateMessages/MessagePrivateMessagesPrivmsgParser.hpp"
#include "code/source/MessageParser/ServerMessages/MessageServerAdminParser.hpp"
#include "code/source/MessageParser/ServerMessages/MessageServerInfoParser.hpp"
#include "code/source/MessageParser/ServerMessages/MessageServerMotdParser.hpp"
#include "code/source/MessageParser/ServerMessages/MessageServerSqueryParser.hpp"
#include "code/source/MessageParser/ServerMessages/MessageServerStatsParser.hpp"
#include "code/source/MessageParser/ServerMessages/MessageServerTimeParser.hpp"
#include "code/source/MessageParser/ServerMessages/MessageServerVersionParser.hpp"
#include "code/source/MessageParser/TestMessages/MessageTestSampleParser.hpp"
#include "code/source/MessageParser/UserMessages/MessageUserErrorParser.hpp"
#include "code/source/MessageParser/UserMessages/MessageUserKillParser.hpp"
#include "code/source/MessageParser/UserMessages/MessageUserPingParser.hpp"
#include "code/source/MessageParser/UserMessages/MessageUserPongParser.hpp"
#include "code/source/MessageParser/UserMessages/MessageUserWhoisParser.hpp"
#include "code/source/MessageParser/UserMessages/MessageUserWhoParser.hpp"
#include "code/source/MessageParser/UserMessages/MessageUserWhowasParser.hpp"


#endif
